# Generated by Django 5.0.6 on 2024-07-02 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_blocklistentry_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blocklistentry',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='blocklistentry',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='blocklistentry',
            name='user',
        ),
    ]
