# Generated by Django 5.1.7 on 2025-03-23 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_blocklistitem_delete_blocklistentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlocklistItem',
        ),
    ]
